#!/bin/sh
# Generate lt__PROGRAM__LTX_preloaded_symbols for the embedded pulseaudio modules.
#
# Reads `nm -g --defined-only` output on stdin and writes C source to stdout.
# Each module object was compiled with -DPA_MODULE_NAME=<module>, which renames
# pa__init/pa__done/pa__get_* to <module>_LTX_pa__* (see module.h). We group
# those symbols by their "<module>" prefix (everything before "_LTX_pa__") and
# emit, for each module, one preopen archive marker ("<module>.a") followed by
# a {name, address} entry per symbol. This is exactly the flat layout that
# libltdl's preopen.c (vm_open/vm_sym) and ltdl.c (try_dlopen) expect.

cat <<'EOF'
/* Generated by gen-pulse-preload.sh -- do not edit. */
#include <ltdl.h>

EOF

awk '
/_LTX_pa__/ {
    sym = $NF;
    idx = index(sym, "_LTX_pa__");
    if (idx <= 1)
        next;
    prefix = substr(sym, 1, idx - 1);
    if (!(prefix in seen)) { seen[prefix] = 1; order[++n] = prefix; }
    cnt[prefix]++;
    symlist[prefix, cnt[prefix]] = sym;
}
END {
    for (i = 1; i <= n; i++) {
        p = order[i];
        for (j = 1; j <= cnt[p]; j++)
            printf "extern void %s(void);\n", symlist[p, j];
    }
    print "";
    print "LT_DLSYM_CONST lt_dlsymlist lt__PROGRAM__LTX_preloaded_symbols[] = {";
    print "    { \"@PROGRAM@\", NULL },";
    for (i = 1; i <= n; i++) {
        p = order[i];
        printf "    { \"%s.a\", NULL },\n", p;
        for (j = 1; j <= cnt[p]; j++)
            printf "    { \"%s\", (void *) %s },\n", symlist[p, j], symlist[p, j];
    }
    print "    { NULL, NULL }";
    print "};";
}
'
