/* lt_dlpreload.c — preloaded loader list for the Windows static build.
 * Normally generated by libtool; hand-written here since we build without
 * libtool. Registers the LoadLibrary loader via the preopen loader in
 * lt_dlinit(). */
#include "ltdl.h"
#include "lt_dlloader.h"

extern lt_dlvtable *loadlibrary_LTX_get_vtable (lt_user_data loader_data);

LT_DLSYM_CONST lt_dlsymlist lt_libltdl_LTX_preloaded_symbols[] = {
    { "libltdl", NULL },
    { "loadlibrary", NULL },
    { "get_vtable", (void *) loadlibrary_LTX_get_vtable },
    { NULL, NULL }
};
